In [1]:
import numpy as np

class Perceptron(object):
    def __init__(self,input_size,lr=1,epochs=10):
        self.W=np.zeros(input_size+1)
        self.epochs=epochs
        self.lr=lr
    def activation_fn(self,x):
        return 1 if x>=0 else 0
    def predict(self,x):
        x=np.insert(x,0,1)
        z=self.W.dot(x)
        a=self.activation_fn(z)
        return a
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

### 1.soru:
def activation_fn(self,x)-> Aktivasyon işlemini uygular. Gelen x 0'dan büyük veya eşitse 1 küçükse 0 döndürür.

def predict(self,x)-> W'nin transpozunu alıyor.Bunu en başına 1 koyduğu x ile çarpıyor ve tek bir değer üretiyor. Daha sonra bunu da activation_fn(self,x)'a gönderiyor.

def fit(self, X, d)-> X ve d yi alıp W'yi belirliyor(W'lerin güncellenmesi).Bunu bir epochs ile yapıyor. 

### 2.soru:

In [2]:
perceptron = Perceptron(input_size=2)

In [3]:
#2.Soru
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
d=np.array([0, 1, 1, 0])
perceptron.fit(X, d)
print(perceptron.W)


[ 0. -1.  0.]


### 3.soru:
Input, yükseklik-genişlik değerleri m,n ise mxnx3 bir veri olur.Bunu vektör olarak düşünüyoruz ve image_1.reshape(mxnx3,1) ile sütun vektör olarak gösteriyoruz. X, 40 imza için her bir sütunda 1 kişiye ait imza resmi olmak üzere (mxnx3,40)'lık bir matris olacaktır, d ise 40 farklı değer olacaktır.

### 4.soru:
Perceptron için input iki tane bool değerdir.Çıktı ise iki bool input değerine karşılık bir sonuç. Ancak imza olayında input (mxnx3,40) lık bir matris ve çıktı ise 40 farklı değerdir. Perceptron bunu tanıma yeteneğine sahip değildir.


In [18]:
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

In [19]:
d = np.array([0, 0, 0, 1])

In [21]:
perceptron.W

array([0., 0., 0.])

In [22]:
perceptron.fit(X, d)

In [23]:
print(perceptron.W)

[-3.  2.  1.]


In [10]:
mp=Perceptron(5)
x=np.asarray([1,2,3,4,5]) #ndarray dim different
x

array([1, 2, 3, 4, 5])

In [11]:
mp.predict(x)

1

In [6]:
mp.activation_fn(-10)

0

In [3]:
mp.W

array([0., 0., 0., 0., 0., 0.])